### ISSUE TITLE
Layout crashes in MvvmCross

### ISSUE THREAD

**Issue by martijn00** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#7]
Error log:

``` c#
[MvxBind]  16.61 Exception during creation of com.refractored.fab.FloatingActionButton from type com.refractored.fab.FloatingActionButton - exception TargetInvocationException: Exception has been thrown by the target of an invocation.
[MvxBind]     at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001c] in <filename unknown>:0 
[MvxBind]   at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00095] in <filename unknown>:0 
[MvxBind]   at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
[MvxBind]   at System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00180] in <filename unknown>:0 
[MvxBind]   at System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) [0x00007] in <filename unknown>:0 
[MvxBind]   at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <filename unknown>:0 
[MvxBind]   at Cirrious.MvvmCross.Binding.Droid.Binders.MvxAndroidViewFactory.CreateView (System.String name, Android.Content.Context context, IAttributeSet attrs) [0x00032] in <filename unknown>:0 
[MvxBind] InnerException was ClassNotFoundException: Exception of type 'Java.Lang.ClassNotFoundException' was thrown.
[MvxBind]     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MvxBind]   at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:195 
[MvxBind]   at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue[] parms) [0x0001d] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:203 
[MvxBind]   at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x00007] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:493 
[MvxBind]   at Android.Runtime.JNIEnv.FindClass (System.Type type) [0x00009] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:434 
[MvxBind]   --- End of managed exception stack trace ---
[MvxBind] java.lang.ClassNotFoundException: Didn't find class "md59838dde1dfda7c80f6571ec8454ca90e.FloatingActionButton" on path: DexPathList[[zip file "/data/app/org.abc.apk"],nativeLibraryDirectories=[/data/app-lib/org.abc-2, /system/lib]]
[MvxBind]   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[MvxBind]   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
[MvxBind]   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
[MvxBind]   at md526640ad76fe23f68c2347e9ddd4c5a15.MvxBindingLayoutInflatorFactory.n_onCreateView(Native Method)
[MvxBind]   at md526640ad76fe23f68c2347e9ddd4c5a15.MvxBindingLayoutInflatorFactory.onCreateView(MvxBindingLayoutInflatorFactory.java:29)
[MvxBind]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
[MvxBind]   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
[MvxBind]   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
[MvxBind]   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
```

**Comment by jamesmontemagno** [comment]
Do you have a sample project to share. I have not kept up to date with MvvmCross so will not have time to repo this.

What does your AXML look like?

**Comment by martijn00** [comment]
Found the reason behind it. This explains the error in MvvmCross: https://github.com/MvvmCross/MvvmCross/issues/981
